<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <title>Cadastro Veículo</title>
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-secondary p-0 ">
            <!-- <a class="navbar-brand" href="#" width="10" height="10" >
                <img src="../assets/img/detran-sc.gif">
            </a> -->
            <a class="navbar-brand ml-4" href="/">Home Pátio</a>
        </nav>
    </header>
    <div class="container mt-5">

        <div class="input-group mb-3 p-0 justify-content-center">
            <form method="post" action="/cadastroVeiculo/" class="col-10">
                <h1 class="text-center"> Cadastrar Veículo</h1>
                <!-- Input tipo do veículo -->
                <div class="input-group mb-3 mt-5">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Tipo do Veículo</span>
                    </div>
                   <select name="tipo">
                       
                   <?php 
                    foreach ($tipo as $key => $value) {
                        echo' <option value="'.$tipo[$key]["id"].'">'.$tipo[$key]["tipo"].'</option>';
                    }
                   ?>
                
                   </select>
                </div>
                    
                <!-- Placa do veículo  -->
                <div class="input-group mb-3 mt-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Placa do Veículo</span>
                    </div>
                    <input type="text" name="placa" class="form-control" placeholder="EXP-7686 " aria-label="Username" aria-describedby="basic-addon1">
                </div>

                <!-- Input marca  -->
                <div class="input-group mb-3 mt-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Marca Veículo</span>
                    </div>
                    <input type="text" name="marca" class="form-control" placeholder="Fiat" aria-label="Username" aria-describedby="basic-addon1">
                </div>
                <!-- input modelo  -->
                <div class="input-group mb-3 mt-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Modelo Veículo</span>
                    </div>
                    <input type="text" name="modelo" class="form-control" placeholder="Mobi " aria-label="Username" aria-describedby="basic-addon1">
                </div>
                <button type="submit">Cadastrar</button>
            </form>
        </div>
    </div>

</body>

</html>