<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <title>Cadastro Veículo</title>
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-secondary p-0 ">
            <!-- <a class="navbar-brand" href="#" width="10" height="10" >
                <img src="../assets/img/detran-sc.gif">
            </a> -->
            <a class="navbar-brand ml-4" href="/">Home Pátio</a>
        </nav>
    </header>
  <div class="container mt-5">
      <div class="col-12"> <h1>asdasdasd</h1> </div>
    <div class="input-group mb-3 p-0 justify-content-center">
        <form method="post" class="col-10" enctype="multipart/form-data">

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">@</span>
                </div>
                <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
            </div>
    </div>
    </form>
    </div>
    
</body>

</html>