<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <title>Consulta</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-secondary p-0 ">

            <a class="navbar-brand ml-4" href="/">Home Pátio</a>
        </nav>
    </header>

    <div class="container mt-5">

   <div class="row">
    <div class="col-12">
        <h1 class="text-center">Consultar Veículos</h1>
    </div> 
    
    <div class="col-12"> 

        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Marca</th>
                    <th scope="col">Modelo</th>
                    <th scope="col">Placa</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                foreach ($veiculos as $key => $value) {
                    echo'
                    <tr>
                        <th scope="row">'.$veiculos[$key]['id'].'</th>
                        <td>'.$veiculos[$key]['tipo'].'</td>
                        <td>'.$veiculos[$key]['marca_veiculo'].'</td>
                        <td>'.$veiculos[$key]['modelo_veiculo'].'</td>
                        <td>'.$veiculos[$key]['placa'].'</td>
                    </tr>
                                     
                    ';
                }
                
                ?>
            </tbody>
        </table>

    </div>

   </div>



    </div>


</body>

</html>