<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
    <title>Editar Veículo</title>
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-secondary p-0 ">

            <a class="navbar-brand ml-4" href="/">Home Pátio</a>
        </nav>
    </header>
    <div class="container mt-5">

        <div class="input-group mb-3 p-0 justify-content-center">
            <h1 class="text-center"> Editar Veículo</h1>
            <div class="col-12">

                <form method="get" action="/editar-veiculo/">

                    <label>ID do veículo</label>
                    <input name="id" type="number" class="form-control">
                    <button type="submit">Selecionar</button>

                </form>
            </div>
            <form method="post" action="/editar-veiculo/" class="col-10">

                <!-- envia o id pro front -->            
                <input name="veiculo" type="hidden" value="<?php echo $id_veiculo; ?>">

                <!-- Input tipo do veículo -->
                <div class="input-group mb-3 mt-5">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Tipo do Veículo</span>
                    </div>
                    <select name="tipo">

                        <?php
                        foreach ($tipo as $key => $value) {
                            $selecionado = "";
                            if ( $tipoID == $tipo[$key]["id"]) {$selecionado = 'selected';}
                            echo ' <option ' . $selecionado . ' value="' . $tipo[$key]["id"] . '">' . $tipo[$key]["tipo"] . '</option>';
                        }
                        ?>

                    </select>
                </div>

                <!-- Placa do veículo  -->
                <div class="input-group mb-3 mt-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Placa do Veículo</span>
                    </div>
                    <input type="text" name="placa" value="<?php  echo $placa; ?>" class="form-control" placeholder="EXP-7686 " aria-label="Username" aria-describedby="basic-addon1">
                </div>

                <!-- Input marca  -->
                <div class="input-group mb-3 mt-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Marca Veículo</span>
                    </div>
                    <input type="text" name="marca_veiculo" value="<?php echo $marca_veiculo ?>" class="form-control" placeholder="Fiat" aria-label="Username" aria-describedby="basic-addon1">
                </div>
                <!-- input modelo  -->
                <div class="input-group mb-3 mt-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Modelo Veículo</span>
                    </div>
                    <input type="text" name="modelo_veiculo" value="<?php echo $modelo_veiculo?>" class="form-control" placeholder="Mobi " aria-label="Username" aria-describedby="basic-addon1">
                </div>
                <button type="submit">Editar</button>


            </form>
            <form method="delete" action="/editar-veiculo/">  
            <button type="submit">DELETAR</button>
                <input name="deletar" type="hidden" value="<?php echo $id_veiculo; ?>">         
            </form>
        </div>
    </div>

</body>

</html>