<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css?family=Carter+One|Staatliches&display=swap" rel="stylesheet">
        <title>Pátio Detran</title>
        <style>
            /* body {
                background-color: #E0F2F7;
                margin: 6% 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            } */

      
            
        </style >
    </head>
    <body class="mt-2 text">
        <header>
            <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-secondary p-0">
           
            <a class="navbar-brand ml-4" href="/">Home Pátio</a>        
        </nav>
        </header> 
        <div class="container mt-5 ">
            <section class="text-center"> 
        <h1 class="font-weight-bold"> Pátio Detran</h1>
        <div class=" mt-5"> <h4>Consulte ou cadastre um veículo no pátio</h4> </div>
        <div class="mt-5 col-12 d-flex justify-content-around">
            <a class="btn btn-secondary btn-lg" href="/consulta-veiculo/">Consultar veículo</a>
            <a class="btn btn-primary btn-lg" href="/cadastroVeiculo/">Cadastrar veículo </a>
            <a class="btn btn-secondary btn-lg" href="/editar-veiculo/">Editar veículos </a>
        </section>
        </div>
        </div>
       
    </body>
</html>
